build:
  version: "3.0"

accounts:
  message: "Welcome to bank account related local APIs"
  contactDetails:
    name: "John"
    email: "{cipher}a3aa6773e784faaae5b746c1bd1c347189ef01bbf21d5c02387db0a43c6d7635"
  onCallSupport:
    -(91) 55525 55525
    -(91) 55524 55524
