build:
  version: "1.0"

cards:
  message: "Welcome to bank cards related local APIs in jagaproduction"
  contactDetails:
    name: "jamespeter"
    email: "james@gmail.com"
  onCallSupport:
    -(91) 55525 55525
    -(91) 55524 55524
