build:
  version: "3.0"

loans:
  message: "Welcome to bank loans related local APIs"
  contactDetails:
    name: "John"
    email: "John@gmail.com"
  onCallSupport:
    -(91) 55525 55525
    -(91) 55524 55524
