# This is a YAML-formatted file
# Declare variables to be passed into your templates

deploymentName: cards-deployment
serviceName: cards
appLabel: cards
appName: cards

replicaCount: 1

image:
  repository: jagadeeswari/microservice_cards
  tag: m17

containerPort: 9001

service:
  type: ClusterIP
  port: 9001
  targetPort: 9001

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resourceserver_enabled: false
otel_enabled: true
kafka_enabled: true
