services:
  configserver:
    image: "jagadeeswari/configserver:m8"
    container_name: ms-configserver
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service:  microservice-base-config

  eurekaserver:
    image: "jagadeeswari/eurekaserver:m8"
    container_name: ms-eurekaserver
    ports:
      - "8060:8060"
    healthcheck:
      test: "curl --fail --silent localhost:8060/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  microservice_accounts:
    image: "jagadeeswari/microservice_accounts:m8"
    container_name: ms-accounts
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  microservice_loans:
    image: "jagadeeswari/microservice_loans:m8"
    container_name: ms-loans
    ports:
      - "8070:8070"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  microservice_loan1:
    image: "jagadeeswari/microservice_loans:m8"
    container_name: ms-loans1
    ports:
      - "8072:8070"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  microservice_cards:
    image: "jagadeeswari/microservice_cards:m8"
    container_name: ms-cards
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  jagadeeswari:
    driver: "bridge"