services:
  accountdb:
    container_name: accountdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loandb:
    container_name: loandb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: loandb
    extends:
      file: common-config.yml
      service: microservice-db-config

  carddb:
    container_name: carddb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: carddb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "jagadeeswari/configserver:m7"
    container_name: ms-configserver
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service:  microservice-base-config

  microservice_accounts:
    image: "jagadeeswari/microservice_accounts:m7"
    container_name: ms-accounts
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountdb:3306/accountdb"
    depends_on:
      accountdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  microservice_loans:
    image: "jagadeeswari/microservice_loans:m7"
    container_name: ms-loans
    ports:
      - "8070:8070"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loandb:3306/loandb"
    depends_on:
      loandb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  microservice_cards:
    image: "jagadeeswari/microservice_cards:m7"
    container_name: ms-cards
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://carddb:3306/carddb"
    depends_on:
      carddb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  jagadeeswari:
    driver: "bridge"