services:
  microservice_accounts:
    image: "jagadeeswari/microservice_accounts:m1"
    container_name: ms-accounts
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - jagadeeswari
  microservice_loans:
    image: "jagadeeswari/microservice_loans:m1"
    container_name: ms-loans
    ports:
      - "8070:8070"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - jagadeeswari
  microservice_cards:
    image: "jagadeeswari/microservice_cards:m1"
    container_name: ms-cards
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - jagadeeswari
networks:
  jagadeeswari:
    driver: "bridge"