spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to bank cards related local APIs"
  contactDetails:
    name: "peter"
    email: "peter@gmail.com"
  onCallSupport:
    -(91) 55525 55525
    -(91) 55524 55524
